version: '3.8'

services:
  db:
    image: mysql:8.0
    mem_limit: 256M
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: change_me_root_password
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  wordpress:
    mem_limit: 256M
    depends_on:
      - db
    build:
      context: .
      args:
        - WORK_DIR=${WORK_DIR}
        - EXPOSE_PORT=${EXPOSE_PORT}
    ports:
      - "${EXPOSE_PORT}:443"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      URL: ${URL}
      TABLE_PREFIX: ${TABLE_PREFIX}
    volumes:
      - ./wordpress:${WORK_DIR}/
      - ./script.sh:/usr/local/bin/script.sh
      - ./.env:${WORK_DIR}/.env
      - ./backup.sql:/root/backup.sql
      - ./old_db.sql:/root/old_db.sql
      - ./.ssh:/root/.ssh
      - ./wp-config.php:/root/wp-config.php
      - ./wp-cli.yml:/root/wp-cli.yml
volumes:
  db_data: {}
