version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: change_me_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpdbuser
      MYSQL_PASSWORD: change_me_db_password

  wordpress:
    depends_on:
      - db
    build:
      context: .
      args:
        - GITLAB_USERNAME=${GITLAB_USERNAME}
        - GITLAB_TOKEN=${GITLAB_TOKEN}
    ports:
      - "8000:443"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpdbuser
      WORDPRESS_DB_PASSWORD: change_me_db_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html/mysite/
      - ./script.sh:/usr/local/bin/script.sh
      - ./backup.sql:/root/backup.sql
      - ./.ssh:/root/.ssh
      - ./wp-config.php:/root/wp-config.php
      - ./wp-cli.yml:/root/wp-cli.yml
volumes:
  db_data: {}